import type {  Dictionary } from "./types";

export const DICTIONARIES: Record<string, Dictionary> = {
  default: {
    create: "Създай Тест",
    heroTitle: "Създавай тестове с лекота",
    heroDescription:
      "Проектирайте, създавайте и експортирайте професионални тестове за минути. Идеален за учители, обучители и любители на викторини.",
    heroMainButton: "Започване",
    heroSecondaryButton: "Научи повече",
    featuresText: "Характеристики",
    feat1Title: "Лесно създаване на тестове",
    feat1Description:
      "Интуитивен интерфейс за създаване на тестове с различни типове въпроси.",
    feat2Title: "Експортиране към PDF",
    feat2Description: "Експортирайте тестовете си като професионални PDF документи.",
    sectionTitle: "Започнете още днес",
    sectionSubTitle: "Създайте тест с помощта на нашия уебсайт безплатно!",
    sectionDescription:
      "Уебсайтът е в процес на интензивна разработка и в бъдеще може да поиска да се регистрирате.",
    backButton: "Назад",
    createNewTitle: "Създай нов тест",
    quizTitlePlaceholder: "Име на теста",
    quizShowDescription:"Показване в PDF-a?",
    quizDescriptionPlaceholder: "Въведете описание на теста",
    quizColumnsPlaceholder: "Колко колони на един ред",
    quiz1Col: "1 Колона",
    quiz2Col: "2 Колони",
    quiz3Col:"3 Колони",
    quizGradingShow:"Скала за оценяване",
    questionAdd:"Добавяне на въпрос",
    quizSave:"Запазване като PDF",
  },
  en: {
    create: "Create Quiz",
    heroTitle: "Create Quizzes with Ease",
    heroDescription:
      "Design, build, and export professional quizzes in minutes. Perfect for teachers, trainers, and quiz enthusiasts.",
    heroMainButton: "Get Started",
    heroSecondaryButton: "Learn More",
    featuresText: "Features",
    feat1Title: "Easy Quiz Creation",
    feat1Description:
      "Intuitive interface for creating quizzes with various question types.",
    feat2Title: "PDF Export",
    feat2Description: "Export your quizzes as professional PDF documents.",
    sectionTitle: "Get Started Today",
    sectionSubTitle: "Create a quiz using our website for free!",
    sectionDescription:
      "The website is under heavy development and may want you to sign up in the future.",
    backButton: "Back",
    createNewTitle: "Create New Quiz",
    quizTitlePlaceholder: "Enter quiz title",
    quizShowDescription:"Show in PDF?",
    quizDescriptionPlaceholder: "Enter quiz description",
    quizColumnsPlaceholder: "How many columns per row",
    quiz1Col: "1 Column",
    quiz2Col: "2 Columns",
    quiz3Col:"3 Columns",
    quizGradingShow:"Grading Scale",
    questionAdd:"Add Question",
    quizSave:"Save as PDF",
  },
  bg: {
    create: "Създай Тест",
    heroTitle: "Създавай тестове с лекота",
    heroDescription:
      "Проектирайте, създавайте и експортирайте професионални тестове за минути. Идеален за учители, обучители и любители на викторини.",
    heroMainButton: "Започване",
    heroSecondaryButton: "Научи повече",
    featuresText: "Характеристики",
    feat1Title: "Лесно създаване на тестове",
    feat1Description:
      "Интуитивен интерфейс за създаване на тестове с различни типове въпроси.",
    feat2Title: "Експортиране към PDF",
    feat2Description: "Експортирайте тестовете си като професионални PDF документи.",
    sectionTitle: "Започнете още днес",
    sectionSubTitle: "Създайте тест с помощта на нашия уебсайт безплатно!",
    sectionDescription:
      "Уебсайтът е в процес на интензивна разработка и в бъдеще може да поиска да се регистрирате.",
    backButton: "Назад",
    createNewTitle: "Създай нов тест",
    quizTitlePlaceholder: "Име на теста",
    quizShowDescription:"Показване в PDF-a?",
    quizDescriptionPlaceholder: "Въведете описание на теста",
    quizColumnsPlaceholder: "Колко колони на един ред",
    quiz1Col: "1 Колона",
    quiz2Col: "2 Колони",
    quiz3Col:"3 Колони",
    quizGradingShow:"Скала за оценяване",
    questionAdd:"Добавяне на въпрос",
    quizSave:"Запазване като PDF",
  },
};
